backend/Modules/Eg/models/Visit.php
<?php

namespace backend\Modules\Eg\models;

use Yii;
use yii\behaviors\SluggableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the model class for table "{{%eg_visit}}".
 *
 * @property int $id
 * @property int $type_fk
 * @property int $id_patient_fk
 * @property int $id_doctor_fk
 * @property int $is_confirm
 * @property string $visit_date
 * @property string $visit_day
 * @property string $visit_time
 * @property int $visit_duration
 * @property int $id_parent_fk
 * @property string $note
 * @property int $status
 * @property string $created_at
 * @property int $created_by
 * @property string $updated_at
 * @property int $updated_by
 * @property string $deleted_at
 * @property int $deleted_by
 */
class Visit extends \yii\db\ActiveRecord
{
    public $user_action;
    public $fromDate;
    public $fromTime;
    public $toDate;
    public $toTime;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%eg_visit}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type_fk', 'id_visit_type_fk', 'id_patient_fk', 'id_doctor_fk', 'is_confirm', 'visit_duration', 'id_parent_fk', 'status', 'created_by', 'updated_by', 'deleted_by', 'id_gallery_fk'], 'integer'],
            [['visit_date', 'visit_day', 'created_at', 'updated_at', 'deleted_at', 'fromDate', 'toDate', 'fromTime', 'toTime',], 'safe'],
            [['fromDate'], 'required', 'message' => 'Proszę podać datę rozpoczęcia wizyty', 'when' => function($model) { return ($model->user_action == 'create' || $model->user_action == 'change'); }],
            [['fromTime'], 'required', 'message' => 'Proszę podać godzinę rozpoczęcia wizyty', 'when' => function($model) { return $model->toTime && ($model->user_action == 'create' || $model->user_action == 'change'); }],
            [['toDate'], 'required', 'message' => 'Proszę podać datę zakończenia wizyty', 'when' => function($model) { return ($model->user_action == 'create' || $model->user_action == 'change'); }],
            //[['toTime'], 'required', 'message' => 'Proszę podać godzinę zakończenia wizyty', 'when' => function($model) { return ($model->user_action == 'create' || $model->user_action == 'change'); }],
            [['end'], 'validateDates', 'when' => function($model) { return ($model->user_action == 'create' || $model->user_action == 'change'); }],
            [[/*'start', 'end', */'id_patient_fk', 'id_doctor_fk', 'id_visit_type_fk'], 'required', 'when' => function($model) { return ($model->user_action == 'create' || $model->user_action == 'change'); }],
            [[/*'start', 'end', */'visit_day', 'id_visit_type_fk', 'place_city', 'place_postalcode'], 'required', 'when' => function($model) { return ($model->user_action == 'booking'); }],
            [['additional_info', 'access_code', 'id_gallery_fk'], 'required', 'when' => function($model) { return ($model->user_action == 'gallery'); }],
            [['note', 'additional_info', 'place_city', 'place_postalcode', 'place_address', 'access_code'], 'string'],
            [['visit_time'], 'string', 'max' => 255],
            [['payment_on_account'], 'number']
        ];
    }
    
    public function validateDates(){
		if($this->toTime) {
            if($this->end && $this->start) {
                if($this->end && strtotime($this->end) <= strtotime($this->start)){
                    //$this->addError('date_from','Please give correct Start and End dates');
                    $this->addError('date_to', 'Wprowadź poprawną datę końca');
                }
            }
        } else {
            if($this->toDate && $this->fromDate) {
                if($this->toDate && strtotime($this->toDate) < strtotime($this->fromDate)){
                    //$this->addError('date_from','Please give correct Start and End dates');
                    $this->addError('date_to', 'Wprowadź poprawną datę końca');
                }
            }
        }
	}

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type_fk' => 'Type Fk',
            'id_visit_type_fk' => 'Rodzaj imprezy',
            'id_patient_fk' => 'Klient',
            'id_doctor_fk' => 'Pracownik',
            'is_confirm' => 'Is Confirm',
            'visit_date' => 'Visit Date',
            'visit_day' => 'Dzień imprezy',
            'visit_time' => 'Visit Time',
            'visit_duration' => 'Visit Duration',
            'id_parent_fk' => 'Id Parent Fk',
            'note' => 'Note',
            'id_dict_eg_visit_status_fk' => 'Status',
            'status' => 'Status',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
            'deleted_at' => 'Deleted At',
            'deleted_by' => 'Deleted By',
            'additional_info' => 'Nazwa galerii', //'Dodatkowa informacja',
            'place_city' => 'Miejscowość', 
            'place_postalcode' => 'Kod pocztowy', 
            'place_address' => 'Adres',
            'id_package_fk' => 'Pakiet',
            'payment_on_account' => 'Zaliczka',
            'access_code' => 'Kod dostępu do galerii'
        ];
    }
	
	public function beforeSave($insert) {
        if($this->user_action == 'booking') {
            $this->start = $this->visit_day.' 00:00:00';
        }
        
        if($this->start) {
            $this->visit_date = $this->start;
            $this->visit_day = date('Y-m-d', strtotime($this->start));
            $this->visit_time = date('H:i', strtotime($this->start));
        } else {
            $this->visit_day = $this->fromDate;
            $this->visit_time = $this->fromTime;
        }
        if (parent::beforeSave($insert)) {
			if($this->isNewRecord ) {
				$this->created_by = \Yii::$app->user->id;
			} else { 
				$this->updated_by = \Yii::$app->user->id;  
			}
			return true;
		} else { 				
			return false;
		}
		return false;
	}
    
    public function afterSave($insert, $changedAttributes) {
       /* if (!$insert) {
        }   */
		parent::afterSave($insert, $changedAttributes);
	}
    
    public function behaviors()	{
		return [
			"timestamp" =>  [
                'class' => TimestampBehavior::className(),
				'createdAtAttribute' => 'created_at',
				'updatedAtAttribute' => 'updated_at',
				'value' => new Expression('NOW()'),
            ],
            'coverBehavior' => [
				'class' => \backend\extensions\kapi\imgattachment\ImageAttachmentBehavior::className(),
				// type name for model
				'type' => 'Visit',
				// image dimmentions for preview in widget 
				'previewHeight' => 200,
				'previewWidth' => 300,
				// extension for images saving
				'extension' => 'jpg',
				// path to location where to save images
				'directory' => Yii::getAlias('@webroot') . '/../..' . Yii::$app->params['basicdir'] . '/web/uploads/ugallery/cover',
				//'url' => Yii::getAlias('@web') . '/..'. Yii::$app->params['basicdir'] . '/web/uploads/pages/cover',
                'url' => Yii::$app->params['frontend'] . '/uploads/ugallery/cover',
				// additional image versions
				'versions' => [
					'small' => function ($img) {
						/** @var ImageInterface $img */
						return $img
							->copy()
							->resize($img->getSize()->widen(200));
					},
					'medium' => function ($img) {
						/** @var ImageInterface $img */
						$dstSize = $img->getSize();
						$maxWidth = 800;
						if ($dstSize->getWidth() > $maxWidth) {
							$dstSize = $dstSize->widen($maxWidth);
						}
						return $img
							->copy()
							->resize($dstSize);
					},
				]
			]
        ];
	}
    
    public static function getList($id) {
        $visits = [];
        $visitsSql = "select id, start, additional_info from {{%eg_visit}} where id_dict_eg_visit_status_fk < 6 and id_patient_fk = ".$id." and visit_day <= '".date('Y-m-d')."' order by start desc limit 8";
        $data = \Yii::$app->db->createCommand($visitsSql)->queryAll();
        foreach($data as $key => $visit) {
            $visits[$visit['id']] = date('Y-m-d H:i', strtotime($visit['start'])) . ( ($visit['additional_info']) ? '['.$visit['additional_info'].']' : '');
        }
        
        return $visits;
    }
	
	public function getPresentation() {
		if(!$this->state) $this->state = 1;
        return isset(self::Viewer()[$this->state]) ? self::Viewer()[$this->state] : self::Viewer()[1];
	}
    
    public static function Viewer() {
		$dictTabs = [
						1 => ['label' => 'nowy', 'color' => 'blue', 'icon' => 'exclamation-circle', 'hashColor' => '#03a9f3'],
						3 => ['label' => 'zaplanowany', 'color' => 'purple', 'icon' => 'check', 'hashColor' => '#ab8ce4'],
						5 => ['label' => 'zrealizowany', 'color' => 'green', 'icon' => 'smile', 'hashColor' => '#A0D65A'],
						6 => ['label' => 'odwołany', 'color' => 'orange', 'icon' => 'ban', 'hashColor' => '#f9892e'],
                        7 => ['label' => 'usunięta', 'color' => 'red', 'icon' => 'trash', 'hashColor' => '#FC5B3F'],
				    ];
		return $dictTabs;
	}
	
	public static function getStates() {
		return [1 => 'nowy', 3 => 'zaplanowany', 5 => 'zrealizowany', 6 => 'odwołany'/*, 7 => 'usunięta'*/];
	}
    
    public function getPatient() {
		return $this->hasOne(\backend\Modules\Eg\models\Patient::className(), ['id' => 'id_patient_fk']);
    }
	
	public function getDoctor() {
		return $this->hasOne(\backend\Modules\Company\models\CompanyEmployee::className(), ['id' => 'id_doctor_fk']);
    }
	
	public function getFiles() {
		return [];
	}
	
	public function getNotes() {
		return [];
	}
    
    public function getSaldo() {
        $paymentSql = "select sum(payment) as payment, sum(paid) as paid, sum(discount) as discount from {{%eg_visit_service}} where status = 1 and id_visit_fk = ".$this->id;
        $data = \Yii::$app->db->createCommand($paymentSql)->queryOne();

backend/Modules/Eg/views/visit/_calendar.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\Modules\visit\models\Calvisit */
/* @var $form yii\widgets\ActiveForm */
?>

    
<div class="grid grid--0">
    <div class="col-md-3 col-xs-7">
        <div class="form-group">
            <label class="control-label" for="visit_fromDate">Start</label>
            <input type='text' class="form-control" id="visit_fromDate" name="Visit[fromDate]" value="<?= $model->fromDate ?>"/> 
        </div>
    </div>
    <div class="col-md-3 col-xs-5">
        <div class="form-group">
            <label class="control-label" for="visit-fromTime">&nbsp;</label>
            <div class='input-group date' id='visit_fromTime' >
                <input type='text' class="form-control" name="Visit[fromTime]" value="<?= $model->fromTime ?>"  />
                <span class="input-group-addon bg-grey" title="Ustaw godzinę startu">
                    <span class="fa fa-clock text--white"></span>
                </span>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-xs-7">
        <div class="form-group">
            <label class="control-label" for="visit-toDate">Koniec</label>
            <input type='text' class="form-control" id="visit_toDate" name="Visit[toDate]" value="<?= $model->toDate ?>"/>
        </div>
    </div>
    <div class="col-md-3 col-xs-5">
        <div class="form-group">
            <label class="control-label" for="visit-toTime">&nbsp;</label>
            <div class='input-group date' id='visit_toTime' >
                <input type='text' class="form-control" name="Visit[toTime]" value="<?= $model->toTime ?>" />
                <span class="input-group-addon bg-grey" title="Ustaw godzinę końca">
                    <span class="fa fa-clock text--white"></span>
                </span>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('#visit_fromDate').datetimepicker({ format: 'YYYY-MM-DD', showClear: true, showClose: true }); 
    $('#visit_fromDate').on("dp.change", function (e) {
        minDate = e.date.format('YYYY-MM-DD');
        $('#visit_toDate').val(minDate);
        if( $('#visit_toDate').val() && $('#visit_fromTime > input').val() && $('#visit_toTime > input').val() ) {
            $start = $('#visit_fromDate').val() + ' ' + $('#visit_fromTime > input').val() + ':00';
            $end = $('#visit_toDate').val() + ' ' + $('#visit_toTime > input').val() + ':00';
        }
    });
      
    $('#visit_fromTime').datetimepicker({  format: 'LT', showClear: true, showClose: true });
    $('#visit_fromTime').on("dp.change", function (e) {
        minDate = e.date.add(30, 'minutes').format('HH:mm');
        $('#visit_toTime > input').val(minDate);
        if( $('#visit_toDate').val() && $('#visit_fromDate').val() && $('#visit_toTime > input').val() ) {
            $start = $('#visit_fromDate').val() + ' ' + $('#visit_fromTime > input').val() + ':00';
            $end = $('#visit_toDate').val() + ' ' + $('#visit_toTime > input').val() + ':00';
        }
    });
    $('#visit_toDate').datetimepicker({ format: 'YYYY-MM-DD', showClear: true, showClose: true }); 
    $('#visit_toDate').on("dp.change", function (e) {
        if( $('#visit_fromDate').val() && $('#visit_fromTime > input').val() && $('#visit_toTime > input').val() ) {
            $start = $('#visit_fromDate').val() + ' ' + $('#visit_fromTime > input').val() + ':00';
            $end = $('#visit_toDate').val() + ' ' + $('#visit_toTime > input').val() + ':00';
        }
    });
    $('#visit_toTime').datetimepicker({  format: 'LT', showClear: true, showClose: true });
    $('#visit_toTime').on("dp.change", function (e) {
        if( $('#visit_fromDate').val() && $('#visit_fromTime > input').val() && $('#visit_toDate').val() ) {
            $start = $('#visit_fromDate').val() + ' ' + $('#visit_fromTime > input').val() + ':00';
            $end = $('#visit_toDate').val() + ' ' + $('#visit_toTime > input').val() + ':00';
        }
    });
    
</script>

backend/Modules/Eg/views/visit/_formGallery.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;

use frontend\widgets\files\FilesBlock;
use common\components\CustomHelpers;
use frontend\widgets\company\EmployeesCheck;
use frontend\widgets\crm\SidesTable;

/* @var $this yii\web\View */
/* @var $model app\Modules\Task\models\CalCase */
/* @var $form yii\widgets\ActiveForm */
?>
<?php $form = ActiveForm::begin([
    //'options'=>['class' => 'form-horizontal', 'enctype'=>'multipart/form-data'],
    'enableAjaxValidation'=>false, 'enableClientValidation'=>false, 'enableClientScript'=>false, 'validateOnSubmit' => false,
    //'options' => ['class' => 'modal-grid',  'enableAjaxValidation'=>true, 'enableClientValidation'=>true,  'data-table' => '#table-events','data-target' => "#modal-grid-event"],
    'options' => ['class' => 'modalAjaxForm', 'data-target' => "#modal-grid-item", 'data-table' => "#table-visits"],
    'fieldConfig' => [
        //'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-5\">{error}</div>",
        //'template' => '<div class="grid"><div class="col-sm-2 col-xs-4">{label}</div><div class="col-sm-10 col-xs-8">{input}</div><div class="col-xs-12">{error}</div></div>',
       // 'labelOptions' => ['class' => 'col-lg-2 control-label'],
    ],
]); ?>
    <div class="modal-body calendar-task">
        <div class="content ">
            <?php if($model->id_dict_eg_visit_status_fk == 1) { ?><div class="alert alert-warning">Termin nie został jeszcze potwierdzony</div><?php } ?>
            <?= $form->field($model, 'additional_info')->textInput(['maxlength' => true, 'class' => 'form-control']) ?>
            <?= $form->field($model, 'access_code')->textInput(['maxlength' => true, 'class' => 'form-control', 'readonly' => true]) ?>
        </div>
	</div>
    <div class="modal-footer"> 
      <?= Html::submitButton( 'Dodaj galerię', ['class' => 'btn btn-sm btn-success']) ?>
        <button aria-hidden="true" data-dismiss="modal" class="btn btn-sm btn-default" type="button" >Odrzuć</button>
    </div>
<?php ActiveForm::end(); ?>

<script type="text/javascript">

</script>

backend/Modules/Eg/views/visit/_formService.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\Modules\Task\models\CalCase */
/* @var $form yii\widgets\ActiveForm */
?>

<?php $form = ActiveForm::begin([
        //'options'=>['class' => 'form-horizontal', 'enctype'=>'multipart/form-data'],
        'enableAjaxValidation'=>false, 'enableClientValidation'=>false, 'enableClientScript'=>false, 'validateOnSubmit' => false,
        'options' => ['class' => 'modalAjaxForm', 'data-target' => "#modal-grid-ajax", 'data-table' => '#table-services' ],
        'fieldConfig' => [
            //'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-5\">{error}</div>",
            //'template' => '<div class="grid"><div class="col-sm-2">{label}</div><div class="col-sm-10">{input}</div><div class="col-xs-12">{error}</div></div>',
           // 'labelOptions' => ['class' => 'col-lg-2 control-label'],
        ],
    ]); ?>
<div class="modal-body">
    <div class="grid">
        <div class="col-xs-12"><?= $form->field($model, 'id_service_fk')->dropDownList(ArrayHelper::map(\backend\Modules\Eg\models\Service::getList(), 'id', 'service_name'), ['options' => \backend\Modules\Eg\models\Service::listAttributes(), 'prompt' => '- wybierz -', 'class' => 'select2Modal'] ) ?> </div>
        <!--<div class="col-xs-4"><?= $form->field($model, 'tooth_no')->dropDownList(\backend\Modules\Eg\models\Tooth::listTooths(), ['prompt' => '- wybierz -', 'class' => 'select2Modal'] ) ?> </div>-->
    </div>
    <fieldset><legend>Rozliczenie</legend>
        <div class="grid">
            <div class="col-sm-4 col-xs-12"><?= $form->field($model, 'payment')->textInput(['maxlength' => true, 'class' => 'form-control number']) ?></div>
            <div class="col-sm-4 col-xs-12"><?= $form->field($model, 'paid')->textInput(['maxlength' => true, 'class' => 'form-control number']) ?></div>
            <div class="col-sm-4 col-xs-12"><?= $form->field($model, 'discount')->textInput(['maxlength' => true, 'class' => 'form-control number']) ?></div>
        </div>
    </fieldset>
</div>
<div class="modal-footer">    
    <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
</div>

<?php ActiveForm::end(); ?>
<script type="text/javascript">
	document.getElementById('visitservice-id_service_fk').onchange = function(event) {
        var servicePrice = this.options[this.selectedIndex].getAttribute("data-price");
        document.getElementById('visitservice-payment').value = servicePrice; 
        var discountValue = document.getElementById('visitservice-discount').value; discountValue = (discountValue) ? discountValue : 0;
        document.getElementById('visitservice-paid').value = servicePrice - discountValue; 
    }
    
    document.getElementById('visitservice-discount').onchange = function(event) {
        var servicePrice = document.getElementById('visitservice-payment').value; servicePrice = (servicePrice) ? servicePrice : 0;
        var discountValue = document.getElementById('visitservice-discount').value; discountValue = (discountValue) ? discountValue : 0;
        document.getElementById('visitservice-paid').value = servicePrice - discountValue; 
    }
</script>

backend/Modules/Eg/views/visit/_note.php
<div class="task-comments-list">
    <div class="task-comments-meta">
        <div class="task-comment-thumb">
            <?php $avatar = (is_file(Yii::getAlias('@webroot') . "/../.." . Yii::$app->params['basicdir'] . "/web/uploads/employees/cover/".$model->id_employee_from_fk."/preview.jpg"))?"/uploads/employees/cover/".$model->id_employee_from_fk."/preview.jpg":"/images/default-user.png"; ?>
            <img src="<?= $avatar ?>" alt="user">
        </div>
        <div class="ask-comment-intro">
            <span class="poster-name"><?= $model->user ?></span>
            <!--<span class="poster-tagline">Dodał komentarz</span>-->
            <div class="commnet-post-date"> <?= $model->created_at ?>  </div>
        </div>
    </div>
    <div class="task-user-comments">
        <p>
            <?= $model->note ?>
        </p>
    </div>
</div>

backend/Modules/Eg/views/visit/_search.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\Modules\eg\models\CalCaseSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="cal-case-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'post',
        'id' => 'filter-eg-visits-search',
        'options' => ['class' => 'widget-table-filter', 'data-table' => '#table-visits']
    ]); ?>

    <div class="grid">
        <div class="col-md-2 col-sm-6 col-xs-6">
			<div class="form-group field-visit-start">
				<label for="visit-start" class="control-label">Data od</label>
				<div class='input-group date' id='datetimepicker_date_from'>
					<input type='text' class="form-control" id="visit-start" name="Visit[start]" value="<?= $model->start ?>" />
					<span class="input-group-addon">
						<span class="glyphicon glyphicon-calendar"></span>
					</span>
				</div>
			</div>
		</div>
        <div class="col-md-2 col-sm-6 col-xs-6">
			<div class="form-group field-visit-end">
				<label for="visit-end" class="control-label">Data do</label>
				<div class='input-group date' id='datetimepicker_date_to'>
					<input type='text' class="form-control" id="visit-end" name="Visit[end]" value="<?= $model->end ?>" />
					<span class="input-group-addon">
						<span class="glyphicon glyphicon-calendar"></span>
					</span>
				</div>
			</div>
		</div>
        <div class="col-md-2 col-sm-12 col-xs-12"><?= $form->field($model, 'is_confirm')->dropDownList( [0 => 'niepotwierdzona', 1 => 'potwierdzona'], ['prompt' => ' - wybierz -', 'class' => 'form-control widget-search-list', 'data-table' => '#table-visits', 'data-form' => '#filter-eg-visits-search' ] )->label('Stan') ?></div>        
        <div class="col-md-3 col-sm-6 col-xs-12"><?= $form->field($model, 'id_doctor_fk')->dropDownList(  ArrayHelper::map(\backend\Modules\Company\models\CompanyEmployee::getDoctors(), 'id', 'fullname'), ['prompt' => ' - wybierz -', 'class' => 'form-control widget-search-list select2', 'data-table' => '#table-visits', 'data-form' => '#filter-eg-visits-search' ] ) ?></div>
        <div class="col-md-3 col-sm-6 col-xs-12"><?= $form->field($model, 'id_patient_fk')->dropDownList(  ArrayHelper::map(\backend\Modules\Eg\models\Patient::getList(), 'id', 'fullname'), ['prompt' => ' - wybierz -', 'class' => 'form-control widget-search-list selectAutoComplete',  'data-url' => Url::to('/eg/patient/autocomplete'), 'data-table' => '#table-visits', 'data-form' => '#filter-eg-visits-search' ] ) ?></div>
        <div class="col-md-12 col-sm-12 col-xs-12"><?= $form->field($model, 'id_dict_eg_visit_status_fk')->dropDownList( \backend\Modules\Eg\models\Visit::getStates(), ['prompt' => ' - wybierz -', 'class' => 'form-control widget-search-list chosen-select', 'data-table' => '#table-visits', 'data-form' => '#filter-eg-visits-search', 'multiple' => true ] ) ?></div>        
    </div> 
		
    <!--
    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div> -->

    <?php ActiveForm::end(); ?>

</div>

backend/Modules/Eg/views/visit/_services.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
?>
<h4>Do zapłaty <span id="tmpl-visitPayment" class="text--pink"><?= $model->saldo ?></span></h4>
<div id="toolbar-services" class="btn-group toolbar-table-widget">
        <?= Html::a('<i class="fa fa-plus"></i>Dodaj', Url::to(['/eg/visit/screate', 'id' => $model->id]) , 
                ['class' => 'btn btn-success btn-icon viewModal', 
                 'id' => 'case-create',
                 //'data-toggle' => ($gridViewModal)?"modal":"none", 
                 'data-target' => "#modal-grid-ajax", 
                 'data-form' => "item-form", 
                 'data-table' => "table-services",
                 'data-title' => "<i class='fa fa-plus'></i>Zabieg"
                ]) ?>
    <!--<button class="btn btn-default btn-refresh-table" type="button" title="Odśwież" data-table="#table-services"><i class="glyphicon glyphicon-refresh icon-refresh"></i></button>-->
</div>
<table  class="table table-striped table-items header-fixed table-widget"  id="table-services"
    data-toolbar="#toolbar-services" 
    data-toggle="table-widget" 
    data-show-refresh="yes" 
    data-show-toggle="true"  
    data-show-columns="false" 
    data-show-export="false"  

    data-show-pagination-switch="false"
    data-pagination="true"
    data-id-field="id"
    data-height="300px"
    data-show-footer="false"
    data-side-pagination="server"
    data-row-style="rowStyle"
    data-sort-name="lastname"
    data-sort-order="asc"
    data-method="get"
    data-checkbox-header="false"
    data-search-form="#filter-eg-services-search"
    data-url=<?= Url::to(['/eg/visit/services', 'id' => $model->id]) ?>>
    <thead>
        <tr>
            <th data-field="id" data-visible="false">ID</th>
            <th data-field="service" data-sortable="true">Usługa</th>
            <th data-field="tooth" data-visible="false" data-sortable="true" data-width="30px">Ząb</th>
            <th data-field="payment" data-sortable="true" data-align="right">Do zapłaty</th>
            <th data-field="paid"  data-sortable="true" data-align="right">Zapłacono</th>
            <th data-field="discount"  data-sortable="true" data-align="right">Rabat</th>
            <!--<th data-field="actions" data-events="actionEvents" data-width="60px"></th>-->
        </tr>
    </thead>
    <tbody class="ui-sortable">

    </tbody>

</table>

backend/Modules/Eg/views/visit/printpdf.php
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <link href="<?= \Yii::getAlias('@webroot') ?>/css/_print.css" rel="stylesheet">
 
</head>
<body>
    <div class="wrapper wrapper-content p-xl">
        <div class="ibox-content p-xl">
            <table class="table table-bordered">
                <tbody>
                    <tr><td>Pacjent</td><td><?= $model->patient['fullname'] ?></td></tr>
                    <tr><td>Lekarz</td><td><?= $model->doctor['fullname'] ?></td></tr>
                    <tr><td>Godzina</td><td><?= $model->start ?></td></tr>
                    <tr><td>Informacja</td><td><?= ($model->additional_info) ? $model->additional_info : 'brak dodatkowej informacji' ?></td></tr>
                    <tr><td>Notatka</td><td><?= ($model->note) ? $model->note : 'brak notatki' ?></td></tr>
                </tbody>
                <tfoot>
                    <tr><td colspan="4"><small>Data wydruku: <i><?= date('Y-m-d H:i:s')  ?></i></small></td></tr>
                </tfoot>
            </table>
        </div>
    </div>
</body>
</html>